# Generated by Django 5.2.14 on 2026-05-12 09:32

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('file', models.FileField(upload_to='lectures/', validators=[utils.validators.validate_pdf_file])),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Practical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('file', models.FileField(upload_to='practicals/', validators=[utils.validators.validate_pdf_file])),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
    ]
